framework:
    assets:
        packages:
            admin:
                json_manifest_path: "%kernel.project_dir%/public/build/admin/manifest.json"
            shop:
                json_manifest_path: "%kernel.project_dir%/public/build/shop/manifest.json"
            app.admin:
                json_manifest_path: "%kernel.project_dir%/public/build/app/admin/manifest.json"
            app.shop:
                json_manifest_path: "%kernel.project_dir%/public/build/app/shop/manifest.json"

            bisumTheme:
                json_manifest_path: "%kernel.project_dir%/public/bisum-theme/manifest.json"

                #

            wishlist_shop:
                json_manifest_path: "%kernel.project_dir%/public/build/bitbag/wishlist/shop/manifest.json"
            wishlist_admin:
                json_manifest_path: "%kernel.project_dir%/public/build/bitbag/wishlist/admin/manifest.json"
                
            elasticsearch_shop:
                json_manifest_path: '%kernel.project_dir%/public/build/bitbag/elasticsearch/shop/manifest.json'
