webpack_encore:
    # output_path: '%kernel.project_dir%/public/build/default'
    output_path: '%kernel.project_dir%/public/bisum-theme'
    builds:
        admin: '%kernel.project_dir%/public/build/admin'
        shop: '%kernel.project_dir%/public/build/shop'
        app.admin: '%kernel.project_dir%/public/build/app/admin'
        app.shop: '%kernel.project_dir%/public/build/app/shop'
        bisumTheme: '%kernel.project_dir%/public/bisum-theme'
        
        wishlist_shop: '%kernel.project_dir%/public/build/bitbag/wishlist/shop'
        wishlist_admin: '%kernel.project_dir%/public/build/bitbag/wishlist/admin'
        elasticsearch_shop: '%kernel.project_dir%/public/build/bitbag/elasticsearch/shop'
        
framework:
    assets:
        # json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        json_manifest_path: '%kernel.project_dir%/public/bisum-theme/manifest.json'